### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by MegaGames-Official** [note3crafter/BedWars#3]
The error Code is:

[16:31:53] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\AddEntityPacket::$entityRuntimeId" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164

**Comment by note3crafter** [comment]
I need the Error code Please send me this
Lg TheNote

**Comment by MegaGames-Official** [comment]
The error Code is:

[16:31:53] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\AddEntityPacket::$entityRuntimeId" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164

**Comment by note3crafter** [comment]
I have a Update how to use it :D

**Comment by navaneeth-dev** [comment]
> The error Code is:
> 
> [16:31:53] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\AddEntityPacket::$entityRuntimeId" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164

You need to put all the plugins in virion folder (NOT the plugins folder)

**Comment by note3crafter** [comment]
its working test youself noteland.citybuild.one 19132 :D

**Comment by ClasherNickXD** [comment]
I need help! It doesn't work! The internal server Error code is: [08:31:41] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\AddEntityPacket::$entityRuntimeId" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164

I hope my server ip helps you to fix it:
Ip: 	ClashdenGames.mc-play.net
Port: 25718

Pls help me. 
LG ClasherNickXD

**Comment by inxomnyaa** [comment]
Duplicate of #6 apibossbar muss geupdated werden.

**Comment by note3crafter** [comment]
der fehler wurde nun behoben!
