### ISSUE TITLE
[Shop] Problem

### ISSUE THREAD

**Issue by navaneeth-dev** [note3crafter/BedWars#4]
Firstly InvMenu is not working for me with DEvirion. I had to install a InvMenu patch from poggit. There is no error code but I can drag items from the shop, and I cannot go into sub items of the shop.

The issue is with pocketmine 3.9.0 - 3.9.4 and virion. Please send link for InvMenu i get incompatible API error

**Comment by note3crafter** [comment]
I have uploaded a folder with the working dataien and that with the shop is not a bug you just have to press Shift at the PC version

**Comment by inxomnyaa** [comment]
The issue is that InvMenu has been updated to api 4.0.0 and poggit, for some reason, uses virions with incorrect API version  @sof3 Might be something to consider? (counter-checking API version compatability with plugin.yml)

**Comment by SOF3** [comment]
I should have checked it, but probably the check didn't work. Not interested in fixing bugs in Poggit anymore.
Best solution is to bump the major version when changing supported API. After all, this won't cause a problem with compatibility anyway.

**Comment by inxomnyaa** [comment]
> Not interested in fixing bugs in Poggit anymore.

Interesting, fine though :P

**Comment by note3crafter** [comment]
So after 2 years i updatet this and intrigrate the gameapi and fix bugs! :D
