### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ClasherNickXD** [note3crafter/BedWars#6]
Wenn ich auf das Schild klicke um zu spielen dann kommt da: Internal Server error. Wenn ich in der Konsole jaxjschailue ist der Fehler Code: [08:31:41] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\AddEntityPacket::$entityRuntimeId" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164

Bitte fixt es ich finde nämlich bedwars mega cool👍🏼😎👌🏼

**Comment by ClasherNickXD** [comment]
Bitte fixt es und benachrichtigt m8ch dann wenn ihr es gefixt habt

**Comment by note3crafter** [comment]
Ich sehe da nix von dem  Bedwars PL schick mal alles bitte

**Comment by ClasherNickXD** [comment]
Hier da stand ClasherNickXD addet to rot und dann kahm da der Fehler da ich ja gekickt wurde weil ich auf das Schild [BedWars] (welt name) geklickt habe. Hilft dir das weiter?
[08:31:41] [Server thread/NOTICE]: ClasherNickXD added to Rot

[08:31:41] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\AddEntityPacket::$entityRuntimeId" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164

**Comment by ClasherNickXD** [comment]
Oder was brauchen Sie um es zu fixen?

**Comment by note3crafter** [comment]
ich bracuh wendern den Kompletten code vom 
"internal server error"

**Comment by ClasherNickXD** [comment]
Habe jetzt alles installiert was du mir über Discord gesagt hast aber da steht immer noch internal server error. Für den kompletten Code brauch ich die Konsole aber die geht gerade nicht. Weisst du wie man es schafft den trotzdem zu bekommen?

**Comment by inxomnyaa** [comment]
apibossbar muss geupdated werden.

**Comment by note3crafter** [comment]
Bossbar wurde gefixxt!
