### ISSUE TITLE
Fatal error: Class 'xenialdan\gameapi\Game' not found in /home/BedWars/plugins/BedWars-German-Edition-master/src/xenialdan/BedWars/Loader.php on line 42

### ISSUE THREAD

**Issue by GamerNico2002** [note3crafter/BedWars#9]
Fatal error: Class 'xenialdan\gameapi\Game' not found in /home/BedWars/plugins/BedWars-German-Edition-master/src/xenialdan/BedWars/Loader.php on line 42

**Comment by note3crafter** [comment]
Der Fehler wurde nun behoben!
